/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Main.Partie;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JLabel;

/**
 *
 * @author Warren
 */
public class PanelPartieSynthese extends javax.swing.JPanel implements Observer {

    private Partie partie;

    public PanelPartieSynthese() {
    }

    /**
     * Creates new form PanelPartieSynthese
     *
     * @param laPartie
     */
    public PanelPartieSynthese(Partie laPartie) {
        initComponents();
        partie = laPartie;
        partie.addObserver(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNbCoups = new javax.swing.JLabel();
        nbCoups = new javax.swing.JLabel();
        jLabelScoreA = new javax.swing.JLabel();
        scoreA = new javax.swing.JLabel();
        jLabelScoreB = new javax.swing.JLabel();
        scoreB = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.red, java.awt.Color.cyan, java.awt.Color.lightGray), "Synthèse"));

        jLabelNbCoups.setText("Nombre de coups : ");

        nbCoups.setText("0");

        jLabelScoreA.setText("Score de A : ");

        scoreA.setText("0");

        jLabelScoreB.setText("Score de B : ");

        scoreB.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNbCoups)
                    .addComponent(jLabelScoreA)
                    .addComponent(jLabelScoreB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreB)
                    .addComponent(scoreA)
                    .addComponent(nbCoups))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbCoups)
                    .addComponent(nbCoups))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScoreA)
                    .addComponent(scoreA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScoreB)
                    .addComponent(scoreB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLabel(String choix) {
        JLabel tmp = null;
        switch (choix) {
            case "nbCoups":
                tmp = nbCoups;
                break;
            case "scoreA":
                tmp = scoreA;
                break;
            case "scoreB":
                tmp = scoreB;
                break;
        }
        return tmp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNbCoups;
    private javax.swing.JLabel jLabelScoreA;
    private javax.swing.JLabel jLabelScoreB;
    private javax.swing.JLabel nbCoups;
    private javax.swing.JLabel scoreA;
    private javax.swing.JLabel scoreB;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (partie == o && partie.getNbrCoups() > 0) {
            nbCoups.setText("" + partie.getNbrCoups());
            scoreA.setText("" + partie.getScoreJoueur(0));
            scoreB.setText("" + partie.getScoreJoueur(1));
        }
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
