/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.util.Observable;
import java.util.Observer;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Warren
 */
public class PanelPartieTableau extends javax.swing.JPanel implements Observer {

    private Partie partie;

    /**
     * Creates new form PanelPartieTableau
     */
    public PanelPartieTableau(Partie laPartie) {
        initComponents();
        partie = laPartie;
        partie.addObserver(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Choix A", "Choix B", "Gain A", "Gain B"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        int joueur1 = partie.getGain(partie.getNbrCoups() - 1, 0);
        int joueur2 = partie.getGain(partie.getNbrCoups() - 1, 1);
        String choix1 = "";
        String choix2 = "";
        if (partie == o && partie.getNbrCoups() > 0) {
            if (partie.aCoopere(partie.getNbrCoups()-1, 0) == true) {
                choix1 = "C";
            } else {
                choix1 = "D";
            }
            if (partie.aCoopere(partie.getNbrCoups()-1, 1) == true) {
                choix2 = "C";
            } else {
                choix2 = "D";
            }
        }
        Object[] line = {"" + partie.getNbrCoups(), choix1, choix2, joueur1, joueur2};
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(line);
    }
}
