/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author Warren
 */
public class PanelPartieSynthese extends javax.swing.JPanel {

    /**
     * Creates new form PanelPartieSynthese
     */
    public PanelPartieSynthese() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNbCoups = new javax.swing.JLabel();
        nbCoups = new javax.swing.JLabel();
        jLabelScoreA = new javax.swing.JLabel();
        scoreA = new javax.swing.JLabel();
        jLabelScoreB = new javax.swing.JLabel();
        scoreB = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));

        jLabelNbCoups.setText("Nombre de coups : ");

        nbCoups.setText("-");

        jLabelScoreA.setText("Score de A : ");

        scoreA.setText("-");

        jLabelScoreB.setText("Score de B : ");

        scoreB.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNbCoups)
                    .addComponent(jLabelScoreA)
                    .addComponent(jLabelScoreB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreB)
                    .addComponent(scoreA)
                    .addComponent(nbCoups))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbCoups)
                    .addComponent(nbCoups))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScoreA)
                    .addComponent(scoreA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScoreB)
                    .addComponent(scoreB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNbCoups;
    private javax.swing.JLabel jLabelScoreA;
    private javax.swing.JLabel jLabelScoreB;
    private javax.swing.JLabel nbCoups;
    private javax.swing.JLabel scoreA;
    private javax.swing.JLabel scoreB;
    // End of variables declaration//GEN-END:variables
}
